CapaPresentacionAdmin/Controllers/VerificarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

using CapaEntidad;
using CapaNegocio;
using ClosedXML.Excel;
using System.Globalization;
using System.Data;
using static ClosedXML.Excel.XLPredefinedFormat;
using DateTime = System.DateTime;
using System.Web.Services.Description;
using CapaPresentacionAdmin.filter;
using System.Web.UI;
using Rotativa;

namespace CapaPresentacionAdmin.Controllers
{
  
    
    [Authorize]
    [ValidarSession]
    public class VerificarController : Controller
    {
        private CN_Reporte objReporte = new CN_Reporte();

        // GET: Verificar
        public ActionResult Buscar()
        {
            return View();
        }
        public ActionResult DatosPersonales()
        {
            return View();
        }
        public ActionResult FormacionAcademica()
        {
            return View();
        }
        public ActionResult Capacitaciones()
        {
            return View();
        }
        public ActionResult Idiomas()
        {
            return View();
        }
        public ActionResult ExperienciaLaboral()
        {
            return View();
        }
        public ActionResult DatosLaborales()
        {
            return View();
        }
        public ActionResult Requisitos()
        {
            return View();
        }
        public ActionResult Reporte()
        {
            return View();
        }
        public ActionResult CrearReporte()
        {
            int contador = 0;
            List<Reporte> oLista = new List<Reporte>();
            List<Reporte> oLista2 = new List<Reporte>();
            List<Reporte> oLista3 = new List<Reporte>();

            List<Reporte> eliminar = new List<Reporte>();

            string numero = ((string)Session["numDocumento"]);

            Session["numDocumento"] = numero;

            //oLista = new CN_Reporte().Listar(numero);
            oLista = new CN_Reporte().ListarGenerarPdf(numero);

            foreach(Reporte r in oLista)
            {
                if(contador >= 18)
                {
                    oLista2.Add(r);
                    eliminar.Add(r);                   

                }
                contador++;
            }

            //eliminar
            foreach(Reporte r in eliminar)
            {
                oLista.Remove(r);
            }

            eliminar.Clear();

            contador = 0;
            foreach(Reporte r in oLista2)
            {
                if (contador >= 32)
                {
                    oLista3.Add(r);
                    eliminar.Add(r);                    

                }
                contador++;
            }

            //eliminar
            foreach (Reporte r in eliminar)
            {
                oLista2.Remove(r);
            }

            eliminar.Clear();

            contador = 0;

            PaginasLista objPaginaList = new PaginasLista()
            {
                hoja1 = oLista,
                hoja2 = oLista2,
                hoja3 = oLista3,
            };

            //return View(objPaginaList);

            return new ViewAsPdf("CrearReporte", objPaginaList)
            {
                FileName = "Reporte.pdf",
                PageOrientation = Rotativa.Options.Orientation.Portrait,
                PageSize = Rotativa.Options.Size.A4,
                PageMargins = new Rotativa.Options.Margins { Bottom = 5, Left = 5, Right = 5, Top = 5 }
            };

        }


        //--------------------------------BUSCAR JSONRESULT

        [HttpGet]
        public JsonResult ListarBuscar()
        {
            string numero = "";

            List<Buscar> oLista = new List<Buscar>();

            oLista = new CN_Buscar().Listar(numero);


            //retornamos esto de esta forma porque DataTable asi lo requiere
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Consultar(string documento)
        {
            List<Buscar> oLista = new List<Buscar>();

            oLista = new CN_Buscar().Listar(documento);

            Session["numDocumento"] = "0";

            if (oLista.Count() > 0)
            {
                Session["numDocumento"] = documento;
              
            }


            //retornamos esto de esta forma porque DataTable asi lo requiere
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }




        [HttpPost]
        public ActionResult exportarReporte(string numero)
        {
            List<Buscar> oLista = new List<Buscar>();

            oLista = new CN_Buscar().Listar(numero);

            //dt es de tipo tabla
            DataTable dt = new DataTable();

            dt.Locale = new System.Globalization.CultureInfo("es-CO");

            dt.Columns.Add("IdPersona", typeof(int));
            dt.Columns.Add("Cedula", typeof(int));
            dt.Columns.Add("Nombre", typeof(string));
            dt.Columns.Add("Genero", typeof(string));
            dt.Columns.Add("FechaNacimiento", typeof(string));
            dt.Columns.Add("CorreoElectronico", typeof(string));
            dt.Columns.Add("Telefono", typeof(string));
            dt.Columns.Add("Sindicato", typeof(string));
            dt.Columns.Add("Profesion", typeof(string));
            dt.Columns.Add("Actividad", typeof(string));
            dt.Columns.Add("FechaIngreso", typeof(string));
            dt.Columns.Add("FechaRetiro", typeof(string));
            dt.Columns.Add("Estado", typeof(int));
            dt.Columns.Add("Verificado", typeof(string));

            foreach (Buscar rp in oLista)
            {
                dt.Rows.Add(new object[]
                {
                    rp.IdPersona,
                    rp.Cedula,
                    rp.Nombre,
                    rp.Genero,
                    rp.FechaNacimiento,
                    rp.CorreoElectronico,
                    rp.Telefono,
                    rp.Sindicato,
                    rp.Profesion,
                    rp.Actividad,
                    rp.FechaIngreso,
                    rp.FechaRetiro,
                    rp.Estado,
                    rp.Verificado,
                });
            }

            dt.TableName = "datos";

            //creamos el doumento excel
            using (XLWorkbook wb = new XLWorkbook())
            {
                var hoja = wb.Worksheets.Add(dt);

                //vamos a guardar el documento en el memorystream
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Reporte" + DateTime.Now.ToString() + ".xlsx");
                }
            }
        }

        //--------------------------------LISTAR DATOS PERSONALES Y DEMAS
        [HttpGet]
        public JsonResult ListarDatosPersonales()
        {

            List<FormacionAcademica> oLista = new List<FormacionAcademica>();

            string numero = ((string)Session["numDocumento"]);

            Session["numDocumento"] = numero;

            oLista = new CN_FormacioAc_Cursos().ListarFormacion(numero);

            //Session["InfoCPersona"] = oLista;
            //List<InfoCPersona> hola = ((List<InfoCPersona>)Session["InfoCPersona"]);

            //retornamos esto de esta forma porque DataTable asi lo requiere
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        //--------------------------------FORMACION ACADEMICA
        [HttpGet]
        public JsonResult ListarFAcademica()
        {

            FormacionAcademica oLista;

            string numero = ((string)Session["numDocumento"]);

            Session["numDocumento"] = numero;


            //oLista = new CN_InfoCPersona().Listar(numero);
            oLista = new CN_FormacioAc_Cursos().ListarFormacion(numero).Where((Ra) => Ra.NumeroDocumento == int.Parse(numero)).FirstOrDefault();

            if (oLista == null)
            {
                oLista = new FormacionAcademica();
                if (string.IsNullOrEmpty(oLista.ObservacionBasica) && string.IsNullOrEmpty(oLista.ObservacionSuperior))
                {
                    oLista.ObservacionBasica = "Debes Hacer una consulta";
                    oLista.ObservacionSuperior = "Debes Hacer una consulta";
                }
            }

            if (string.IsNullOrEmpty(oLista.ObservacionBasica) && string.IsNullOrEmpty(oLista.ObservacionSuperior))
            {
                oLista.ObservacionBasica = "Agrega un Comentario";
                oLista.ObservacionSuperior = "Agrega un Comentario";
            }

            if (string.IsNullOrEmpty(oLista.CumpleBasica) && string.IsNullOrEmpty(oLista.CumpleSuperior))
            {
                oLista.CumpleBasica = "Sin Seleccionar";
                oLista.CumpleSuperior = "Sin Seleccionar";
            }


            //retornamos esto de esta forma porque DataTable asi lo requiere
            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult EditarFormacioAcademica(int IdFAcademica, string Numero, string Cumple, string Observacion)
        {
            //nos permite guarda cualquier tipo de datos
            bool resultado;
            FormacionAcademica oLista;
            string mensaje = string.Empty;

            string numero = ((string)Session["numDocumento"]);

            Session["numDocumento"] = numero;

            oLista = new CN_FormacioAc_Cursos().ListarFormacion(numero).Where((Ra) => Ra.NumeroDocumento == int.Parse(numero)).FirstOrDefault();

            if (oLista == null)
            {
                resultado = false;
                mensaje = "Debes consultar una persona primero";

CapaPresentacionAdmin/Views/Verificar/Buscar.cshtml
@{
    ViewBag.Title = "Buscar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="mb-3 mt-2">
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow p-3 mb-4 bg-body rounded border border-1" style="width:100%">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="@Url.Action("Buscar","Verificar")">Buscar</a>
                    <a class="nav-link" href="@Url.Action("DatosPersonales","Verificar")">Datos Personales</a>
                    <a class="nav-link" href="@Url.Action("FormacionAcademica","Verificar")">Formacion Academica</a>
                    <a class="nav-link" href="@Url.Action("Capacitaciones","Verificar")">Cursos</a>
                    <a class="nav-link" href="@Url.Action("Idiomas","Verificar")">Idiomas</a>
                    <a class="nav-link" href="@Url.Action("ExperienciaLaboral","Verificar")">ExLaboral</a>
                    <a class="nav-link" href="@Url.Action("DatosLaborales","Verificar")">Datos Laborales</a>
                    <a class="nav-link" href="@Url.Action("Requisitos","Verificar")">Requisitos</a>
                    <a class="nav-link" href="@Url.Action("Reporte","Verificar")">Reporte</a>
                </div>
            </div>
        </div>
    </nav>
</div>
<div class="card">
    <div class="card-header">
        <i class="fas fa-briefcase"></i> <span class="text-secondary">Verificar Hoja De Vida/ Buscar</span>
    </div>
    <div class="card-body">
        <div class="row">
            <form class="mb-3" action="@Url.Action("exportarReporte","Verificar")" method="post">
                <div class="row align-items-end">
                    <div class="col-sm-3">
                        <label for="txtConsultar" class="form-label">Numero de Documento:</label>
                        <input type="text" class="form-control" id="txtConsultar" value="">
                    </div>
                    <div class="col-sm-3">
                        <button id="btnconsultar" type="button" class="btn btn-primary ">Consultar</button>
                        <button id="btnexportar" type="submit" class="btn btn-success" name="numero"><i class="fas fa-file-excel mx-1"></i>Exportar</button>
                    </div>
                </div>
            </form>
        </div>
        <style>
            #miTabla_wrapper {
                overflow-x: auto;
            }
        </style>
        <div class="miTabla_wrapper">
            <table id="tabla" class="cell-border table-responsive">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Cédula</th>
                        <th>Nombre</th>
                        <th>Género</th>
                        <th>Fecha Nac.</th>
                        <th>Correo</th>
                        <th>Telefono</th>
                        <th>Sindicato</th>
                        <th>Profesión</th>
                        <th>Actividad</th>
                        <th>Fec. Ingreso</th>
                        <th>Fec. Retiro</th>
                        <th>Estado</th>
                        <th>Verificado</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>       
    </div>
</div>
<div class="modal fade" id="modalresult" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Mensaje</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">

                Operación exitosa
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts{

    <script>

        var tabladata

        var Url = '@Url.Action("ListarBuscar", "Verificar")'

        $(document).ready(function () {
            tabladata = $("#tabla").DataTable({
                /*responsive: true,*/
                scrollX: true,
                ordering: false,
                "ajax": {
                    url: Url,
                    type: "GET",
                    dataType: "json",
                },
                "columns": [
                    { "data":"IdPersona" },
                    { "data": "Cedula" },
                    { "data": "Nombre" },
                    { "data": "Genero" },
                    { "data": "FechaNacimiento" },
                    { "data": "CorreoElectronico" },
                    { "data": "Telefono" },
                    { "data": "Sindicato" },
                    { "data": "Profesion" },
                    { "data": "Actividad" },
                    { "data": "FechaIngreso" },
                    { "data": "FechaRetiro" },
                    { "data": "Estado" },
                    { "data": "Verificado" },

                ],
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.13.3/i18n/es-ES.json"
                }
            })

            $("#btnconsultar").on("click", function () {

                var nueva_url = '@Url.Action("Consultar", "Verificar")' +
                "?documento=" + $("#txtConsultar").val()

                tabladata.ajax.url(nueva_url).load();
                /*$("#modalresult").modal("show")*/
            })

        });


    </script>

}

CapaPresentacionAdmin/Views/Verificar/Capacitaciones.cshtml
@{
    ViewBag.Title = "Capacitaciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="mb-3 mt-2">
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow p-3 mb-4 bg-body rounded border border-1" style="width:100%">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="@Url.Action("Buscar","Verificar")">Buscar</a>
                    <a class="nav-link" href="@Url.Action("DatosPersonales","Verificar")">Datos Personales</a>
                    <a class="nav-link" href="@Url.Action("FormacionAcademica","Verificar")">Formacion Academica</a>
                    <a class="nav-link" href="@Url.Action("Capacitaciones","Verificar")">Cursos</a>
                    <a class="nav-link" href="@Url.Action("Idiomas","Verificar")">Idiomas</a>
                    <a class="nav-link" href="@Url.Action("ExperienciaLaboral","Verificar")">ExLaboral</a>
                    <a class="nav-link" href="@Url.Action("DatosLaborales","Verificar")">Datos Laborales</a>
                    <a class="nav-link" href="@Url.Action("Requisitos","Verificar")">Requisitos</a>
                    <a class="nav-link" href="@Url.Action("Reporte","Verificar")">Reporte</a>
                </div>
            </div>
        </div>
    </nav>
</div>
<div class="card">
    <div class="card-header">
        <i class="fas fa-briefcase"></i>  <span class="text-secondary">Verificar Hoja De Vida/ Capacitaciones o Cursos</span>
    </div>
    <div class="card-body">
        <div class="row mb-3">
            <div class="col-3">
                <p class="form-label text-danger" id="idNombrec" style="font-size: 13px">NOMBRE DE LA PERSONA A VERIFICAR</p>
            </div>
            <div class="col-6">
                <p class="form-label" id="idArea" for="validationCustom05" style="font-size:13px">UNION DE EMPLEADOS TRABAJADORES Y CONTRATISTAS DE LA SALUD - UTRASSALUD Gestion Humana Profecional del Talento Humano</p>
            </div>
            <div class="col-3">
                <p class="form-label" id="idverific" for="validationCustom05" style="font-size:13px">Confirmado:</p>
            </div>
        </div>
        <table id="tabla" class="table table-hover mt-4" style="width:100%; font-size:12px">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Tipo Formacion</th>
                    <th>Nombre Formacion</th>
                    <th>Fecha Inicial</th>
                    <th>Fecha Final</th>
                    <th>Ver Adjunto</th>
                    <th>Cumple</th>
                    <th>Observacion</th>
                    <th>......</th>
                </tr>
            </thead>
            <tbody id="bodyCapacitaciones">
            </tbody>
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Actividad</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input id="txtidPersona" type="hidden" value="0" />
                <input id="txtid" type="hidden" value="0" />
                <br />
                <label for="cboCumple" class="form-label mt-1">Cumple:</label>
                <select id="cboCumple" class="form-select" aria-label="Default select example">
                    <option value="Na">Na</option>
                    <option value="Si">Si</option>
                    <option value="No">No</option>
                </select>
                <label for="idObservacion" class="form-label mt-2">Observacion:</label>
                <textarea class="form-control" id="idObservacion"></textarea>

                <div id="mensajeError" class="alert alert-danger mt-2" role="alert">
                    A simple danger alert—check it out!
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


@section scripts{


    <script>

        var filaSeleccionada;
        var tabladata;

        var Url = '@Url.Action("ListarCursos", "Verificar")';


        jQuery.ajax({
            url: '@Url.Action("ListarFAcademica", "Verificar")',
            type: "GET",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                $("#idNombrec").text(response.data.NombreCompleto)
                $("#idverific").text("Confirmado: "+response.data.Verificado)

                if (response.data.Verificado != 'Si') {
                    $('#idNombrec').addClass('text-danger');
                } else {
                    $('#idNombrec').removeClass('text-danger');
                    $('#idNombrec').addClass('text-primary');
                }



            }

        })
        jQuery.ajax({
            url: '@Url.Action("ListarDatosLaborales", "Verificar")',
            type: "GET",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                const dLaboral = response.data[0]
                $("#idArea").text(dLaboral.NombreArea)
               

            }

        })

         jQuery.ajax({
            url: Url,
            type: "GET",
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (response) {

                $.each(response.data, function (i, element) {
                    $("<tr>").append(
                        $("<td>").text(element.idCapacitacionesCursos),
                        $("<td>").text(element.TipoFormacion),
                        $("<td>").text(element.Nombre),
                        $("<td>").text(element.FechaInicio),
                        $("<td>").text(element.FechaFinalizacion),
                        $("<td>").append(
                            $("<form>").attr({ "action": '@Url.Action("verPdfCapaciatciones", "Verificar")', "method": "post", "target":"_blank" }).append(
                                $("<input>").attr({ "type": "hidden", "name": "IdCapacitaciones", "value": element.idCapacitacionesCursos }),
                                $("<button>").addClass("btn btn-outline-success btn-sm mb-2 btn-archivo").attr({ "type": "submit" }).text("Archivo"),

                            ),

                        ),
                        $("<td>").text(element.Cumple),
                        $("<td>").text(element.Observacion),
                        $("<td>").append(
                            $("<button>").addClass("btn btn-outline-success btn-sm btn-editar").attr({ "type": "button", "onclick": "abrirModal()" }).text("Obervacion y Guardar"),
                        ),
                    ).appendTo("#bodyCapacitaciones")

                    $("#txtidPersona").val(element.IdPersona)
                })

                //coneverti en datatable
                tabladata = $("#tabla").DataTable({
                    responsive: true,
                    ordering: false,
                    "language": {
                        "url": "https://cdn.datatables.net/plug-ins/1.13.3/i18n/es-ES.json"
                    }

                })

            }

        })




        function abrirModal(json) {

            $("#txtid").val(0)
            $("#idObservacion").val("")
            $("#cboCumple").val("Sin selecionar")

            $("#mensajeError").hide()



            if (json != null) {
                $("#txtidPersona").val()
                $("#txtid").val(json[0])
                $("#cboCumple").val(json[6])
                $("#idObservacion").val(json[7])

                console.log(json)
            }


            $("#FormModal").modal("show")
        }


        $("#tabla tbody").on("click", '.btn-editar', function () {
            filaSeleccionada = $(this).closest("tr")

            //data es un json porque data() retorna un json
            var data = tabladata.row(filaSeleccionada).data()

            abrirModal(data)

        })


        $("#tabla tbody").on("click", '.btn-archivo', function () {
            filaSeleccionada = $(this).closest("tr")

            //data es un json porque data() retorna un json
            var data = tabladata.row(filaSeleccionada).data()
            console.log(data.Archivo)


        })



        //-----------------------------Guardar
        function Guardar() {
            var IdPersona = $("#txtidPersona").val()
            var IdCurso = $("#txtid").val()
            var Cumple = $("#cboCumple").val()
            var Observacion = $("#idObservacion").val()

            jQuery.ajax({
                url: '@Url.Action("EditarCurso", "Verificar")',
                type: "POST",
                data: JSON.stringify({ IdPersona: IdPersona , IdCurso: IdCurso, Cumple: Cumple, Observacion: Observacion }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    $(".modal-body").LoadingOverlay("hide")

                    if (data.resultado) {
                        $("#FormModal").modal("hide");
                    } else {
                        $("#mensajeError").text(data.mensaje)
                        $("#mensajeError").show()
                    }
                    location.reload();

                },
                error: function (error) {
                    $(".modal-body").LoadingOverlay("hide")
                    $("#mensajeError").text("Error Ajax")
                    $("#mensajeError").show()
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size:14
                    })
                }
            });

        }

    </script>



}